version: "3.8"
services:
  web:
    build:
      context: ./
      dockerfile: ./pysolar/Dockerfile
    image: web:latest
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - ./data:/app/data
